-- ----------------------------
-- 启用 pgvector 向量扩展 (需确保 PostgreSQL 已安装该插件)
-- ----------------------------
DO $$ 
BEGIN
    CREATE EXTENSION IF NOT EXISTS vector;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'pgvector 扩展暂未加载，将继续完成实体关系表结构建立。';
END $$;

-- ----------------------------
-- 1. 知识库主表 sys_knowledge_base
-- ----------------------------
DROP TABLE IF EXISTS sys_knowledge_base CASCADE;
CREATE TABLE sys_knowledge_base (
    id            bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    tenant_id     bigint          NOT NULL DEFAULT 0,         -- 租户ID（0表示集团公共）
    kb_name       varchar(100)    NOT NULL,                   -- 知识库名称
    kb_type       char(1)         NOT NULL DEFAULT '2',       -- 知识库类型（1-集团公共库，2-机构私有库）
    status        char(1)                  DEFAULT '0',       -- 状态（0正常 1停用）
    create_by     varchar(64)              DEFAULT '',        -- 创建者
    create_time   timestamp                                 , -- 创建时间
    update_by     varchar(64)              DEFAULT '',        -- 更新者
    update_time   timestamp                                 , -- 更新时间
    remark        varchar(500)             DEFAULT NULL,      -- 备注
    CONSTRAINT pk_sys_knowledge_base PRIMARY KEY (id)
);

COMMENT ON TABLE sys_knowledge_base IS '知识库主表';
COMMENT ON COLUMN sys_knowledge_base.tenant_id IS '租户ID（0表示集团公共）';
COMMENT ON COLUMN sys_knowledge_base.kb_name IS '知识库名称';
COMMENT ON COLUMN sys_knowledge_base.kb_type IS '知识库类型（1-集团公共库，2-机构私有库）';
COMMENT ON COLUMN sys_knowledge_base.status IS '状态（0正常 1停用）';

CREATE INDEX idx_kb_tenant_id ON sys_knowledge_base (tenant_id);
CREATE INDEX idx_kb_type ON sys_knowledge_base (kb_type);

-- ----------------------------
-- 2. 知识库文档表 sys_knowledge_doc
-- ----------------------------
DROP TABLE IF EXISTS sys_knowledge_doc CASCADE;
CREATE TABLE sys_knowledge_doc (
    id            bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    kb_id         bigint          NOT NULL,                   -- 关联知识库ID
    doc_name      varchar(255)    NOT NULL,                   -- 文档名称
    doc_url       varchar(500)             DEFAULT NULL,      -- 文档存储路径/URL
    version       varchar(50)              DEFAULT 'v1.0',    -- 版本号（如 v2.0）
    effective_date timestamp               DEFAULT NULL,      -- 生效日期
    superseded_id bigint                   DEFAULT NULL,      -- 被替代文档ID
    priority      integer                  DEFAULT 80,        -- 优先级权重（集团默认100，地方库默认80）
    status        char(1)         NOT NULL DEFAULT '0',       -- 状态（0-解析中，1-已生效，2-已禁用/已废止）
    dept_id       bigint                   DEFAULT 0,         -- 归属部门ID（行级权限隔离）
    role_mask     varchar(200)             DEFAULT '',        -- 角色遮罩/权限掩码
    create_by     varchar(64)              DEFAULT '',        -- 创建者
    create_time   timestamp                                 , -- 创建时间
    update_by     varchar(64)              DEFAULT '',        -- 更新者
    update_time   timestamp                                 , -- 更新时间
    remark        varchar(500)             DEFAULT NULL,      -- 备注
    CONSTRAINT pk_sys_knowledge_doc PRIMARY KEY (id),
    CONSTRAINT fk_sys_knowledge_doc_kb FOREIGN KEY (kb_id) REFERENCES sys_knowledge_base (id) ON DELETE CASCADE
);

COMMENT ON TABLE sys_knowledge_doc IS '知识库文档表';
COMMENT ON COLUMN sys_knowledge_doc.kb_id IS '关联知识库ID';
COMMENT ON COLUMN sys_knowledge_doc.doc_name IS '文档名称';
COMMENT ON COLUMN sys_knowledge_doc.version IS '版本号';
COMMENT ON COLUMN sys_knowledge_doc.effective_date IS '生效日期';
COMMENT ON COLUMN sys_knowledge_doc.superseded_id IS '被当前文档替代的旧文档ID';
COMMENT ON COLUMN sys_knowledge_doc.priority IS '优先级权重';
COMMENT ON COLUMN sys_knowledge_doc.status IS '状态（0-解析中，1-已生效，2-已禁用/已废止）';
COMMENT ON COLUMN sys_knowledge_doc.dept_id IS '归属部门ID（行级权限隔离）';

CREATE INDEX idx_doc_kb_id ON sys_knowledge_doc (kb_id);
CREATE INDEX idx_doc_status ON sys_knowledge_doc (status);
CREATE INDEX idx_doc_dept_id ON sys_knowledge_doc (dept_id);
CREATE INDEX idx_doc_effective_date ON sys_knowledge_doc (effective_date);

-- ----------------------------
-- 3. 知识切片表 sys_knowledge_chunk (包含高维向量字段)
-- ----------------------------
DROP TABLE IF EXISTS sys_knowledge_chunk CASCADE;
CREATE TABLE sys_knowledge_chunk (
    id            bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    doc_id        bigint          NOT NULL,                   -- 关联文档ID (级联删除)
    vector_id     varchar(64)     NOT NULL,                   -- 外部 Chunk ID
    page_number   integer                  DEFAULT 1,         -- 所在 PDF/Word 页码
    content       text            NOT NULL,                   -- 切片文本内容
    embedding     text            NOT NULL,                   -- 1024 维向量数据(兼容格式，安装 pgvector 后可转为 vector(1024))
    create_time   timestamp                                 , -- 创建时间
    CONSTRAINT pk_sys_knowledge_chunk PRIMARY KEY (id),
    CONSTRAINT fk_sys_knowledge_chunk_doc FOREIGN KEY (doc_id) REFERENCES sys_knowledge_doc (id) ON DELETE CASCADE
);

COMMENT ON TABLE sys_knowledge_chunk IS '知识切片表';
COMMENT ON COLUMN sys_knowledge_chunk.doc_id IS '关联文档ID (级联物理删除)';
COMMENT ON COLUMN sys_knowledge_chunk.embedding IS '高维文本向量（1024维，用于相似度检索）';

CREATE INDEX idx_chunk_doc_id ON sys_knowledge_chunk (doc_id);

-- 安装 pgvector 插件后解锁以下两行：
-- ALTER TABLE sys_knowledge_chunk ALTER COLUMN embedding TYPE vector(1024) USING embedding::vector;
-- CREATE INDEX idx_chunk_embedding_cosine ON sys_knowledge_chunk USING hnsw (embedding vector_cosine_ops);

